### ISSUE TITLE
Question: What is the difference between the HTML5 version and the server version?

### ISSUE THREAD

**Issue by martinhelfrich** [Biological-Computation/crn-engine#3]
They produce the same interface (at least for ClassicDSD). So what's the difference?

**Comment by ph1ll1ps** [comment]
The HTML5 version is for deployment online and can run entirely in a browser, since it is compiled to JavaScript. The main downside is that Visual DSD model compilation and simulation will be noticeably slower for large models, due to the lower performance of JavaScript compared to Windows binaries. The main advantage is that users can try out the tool online without any installation requirements, including via a phone or tablet. I've just put the HTML5 tool back online at https://ph1ll1ps.github.io/visualdsd/ This runs entirely in the browser on the client, with no server-side component.

**Comment by martinhelfrich** [comment]
Thanks for redeploying the tool. This would have saved me quite some time if I hadn't already set it up myself :)
But others will benefit for sure...
