### ISSUE TITLE
Question: How would one deploy a Server build?

### ISSUE THREAD

**Issue by martinhelfrich** [Biological-Computation/crn-engine#4]
If I just run the .exe that was build, the server only listens to ports from the local machine (127.0.0.1:8084). 
How can I run the server so that it listens to external requests (0.0.0.0:8084)?

For that matter: What if I want to deploy the HTML5 version? Is that easier?

**Comment by martinhelfrich** [comment]
Update:
I got the HTML5 version deployed.
For this I added another dotnet target in ClassicDSDHTML5/build.fsx

```
Target.create "Deploy" (fun _ ->
    runDotNet ("serve -d dist -p "+localPort+" -o -a 0.0.0.0") projectFolder
)
```

Then one can deploy while listening to external calls via
> dotnet fake build --target deploy

One can create a similar shortcut to the run.cmd. Simply copy the file, rename it and change the content to this command.

**Comment by ph1ll1ps** [comment]
See previous related issue about the HTML5 version. Yes, the Server build is configured for local execution and is the primary means of interacting with Visual DSD binaries. The HTML5 version can be deployed as a standard web page since it runs client side in the browser via JavaScript, e.g. see https://ph1ll1ps.github.io/visualdsd/. The server version could be set up to run remotely, though further work would be required. Thanks for sharing your update regarding HTML5 deployment. And thanks for your interest in Visual DSD.
